<a href="https://colab.research.google.com/github/j2cry/hw_DataScienePyLibs/blob/main/hw2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Задание 1.** Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [ ]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

**Задание 2.** Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [ ]:
arrays = []
n = 1
while n <= a.size / 2:    
  if a.size % n == 0:
    arrays.append(a.reshape(int(a.size / n), n))
  n += 1

arrays

[array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

**Задание 3.** Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [ ]:
arrays = []

n = 1
while n <= a.size / 2:
  if a.size % n == 0:
    if n % 2 == 0:
      arrays.append(a.reshape(int(a.size / n), -1))   # for n = 2, 4, 6
    else: 
      arrays.append(a.reshape(-1, n))   # for n = 1, 3
  n += 1

arrays

[array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

**Задание 4.** Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?



> Нельзя. каждая строка это numpy.ndarray



In [ ]:
type(a.reshape(12, 1)[0])

numpy.ndarray

**Задание 5.** Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [ ]:
arr_2d = np.random.normal(size=(3, 4))
arr_1d = arr_2d.flatten()

**Задание 6.** Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [ ]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

**Задание 7.** Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [ ]:
b = np.arange(20, 1, -2)
b
# разницы между этими массивами нет

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

**Задание 8.** Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [ ]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.concatenate((a, b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**Задание 9.** Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [ ]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At) # np.matmul(A, At)  A @ At
print(B.shape)
np.linalg.det(B)

(4, 4)


0.0

> Матрица B вырожденная => вычислить обратную не получится

**Задание 10.** Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [ ]:
np.random.seed(42)

**Задание 11.** Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [ ]:
c = np.random.randint(0, 16, size=16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

**Задание 12.** Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [ ]:
C = c.reshape(4, 4)
D = 10 * C + B
np.linalg.det(D)
np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)

**Задание 13.** Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [ ]:
condition = D_inv <= 0
D_inv[condition] = 0
D_inv[~condition] = 1
D_inv

In [ ]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])